### ISSUE TITLE
[QUEST] Ember Engines with `package` API

### ISSUE THREAD

**Issue by twokul** [ember-engines/ember-engines#568]
Ember Engines proved to be very useful composability primitive: it allows multiple logical applications to be composed together into a single one.

The first iteration of Ember Engines was impacted by the lack of Ember CLI public APIs. That led to quite a few API extensions and using `public` tree to produce engines files.

Moving forward, Ember Engines should take advantage of the new public `package` API that Ember CLI provides. Ember Engines will lean on build pipeline more and will only provide configuration for it. This will result into a more straightforward implementation as well as improve application build speed.

For more context, please read [Ember Engines 1.0 roadmap](https://discuss.emberjs.com/t/engines-1-0-roadmap/14914).

#### Action plan

+ [ ] implement `ember-engines` packager
  + [ ] eager engines (bundled with `vendor.js` files)
  + [ ] lazy loading (bundled separately)
+ [ ] preserve current behaviour and ensure backward compatibility:
  + [ ] `EmberEngine.extend`
  + [ ] `lazyLoading` option
  + [ ] `noManifest` option
  + [ ] fastboot support
  + [ ] testing API (`engineResolverFor`, `asset-manifest`)
  + [ ] eager engines are bundled into the host application's `vendor.js` file
  + [ ] `app` folder should be ignored (files in this folder don't make much sense in the context of engines)
  + [ ] files inside `addon` folder will be bundled into `engine.js` file and will be processed as per addon behaviour
  + [ ] files in  `public` folder should appear at the root of the engine w/o transformation
  + [ ] `asset-manifest.json` must be generated, and a meta tag config should be inserted inside of the host application's `index.html` when `lazyLoading` option is enabled
  + [ ] `import` should work as expected
+ [ ] identify deprecated APIs if any:
  + [ ] `_processedExternalTree` is overriden
  + [ ] `_concatStyles` is overriden
+ [ ] identify missing APIs in `ember-cli` if any; take a closer look at the added `ember-engines` APIs and brainstorm if they are could be extracted/generalized:
  + [ ] `treeForEngine`
  + [ ] `ancestorHostAddons`
  + [ ] `nonDuplicatedAddonInvoke`
  + [ ] `engineConfig`
  + [ ] `getAddonsConfig`
  + [ ] `updateFastBootManifest`
  + [ ] `getEngineConfigContents`
  + [ ] `useDeprecatedIncorrectCSSProcessing`
+ [ ] address test failures

#### Run your application w/ experimental API

1. Clone `ember-cli` and `ember-engines`
2. `yarn link` `ember-cli` and `ember-engines`
3. Make changes to `ember-cli-build` as specified below
4. Run your application with `EMBER_CLI_PACKAGER=true ember serve`

The _working_ version of how to use the new API within a host application:

```javascript
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');
const mergeTrees = require('broccoli-merge-trees');
const packageEngines = require('ember-engines/lib/packager');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    package(fullTree) {
      // `dist/engines-dist` folder
      let enginesDist = packageEngines.call(this, fullTree);

      // regular `assets` folder
      let applicationDist = this.defaultPackage(fullTree);

      return mergeTrees([enginesDist, applicationDist], {
        overwrite: true,
        annotation: 'Application Dist + Engines'
      });
    }
  });

  return app.toTree();
};
```

Once and if we agree on the API above, we could work on providing a codemod which would allow mainless migration.

**Comment by mike183** [comment]
I imagine we’d also need to update the blueprints as part of this work? Both for in-repo engines (in this repo) and standalone engines ([here](https://github.com/ember-engines/engine-blueprint)).

**Comment by twokul** [comment]
@mike183 possibly! afaik, we use `ManifestGenerator` + a bunch of properties in engine's `index.js` file; if that were to change, we would need to update blueprints. I'm not sure it would right now. Or is there something else you were referring to?

**Comment by villander** [comment]
@twokul I look forward to being able to help. Could we best describe each task? Packager API is still very private.

**Comment by mike183** [comment]
@twokul Sorry for the delayed response.

I had just assumed that with a codemod being mentioned that the required changes may also need to be made within the blueprint output?

**Comment by villander** [comment]
@twokul how is it going from here? package API ready to integrate with ember-engines? I'd love to be able to help.

**Comment by villander** [comment]
@twokul @dgeb @rwjblue @MelSumner how is it going from here? package API ready to integrate with ember-engines? I'd love to be able to help.

**Comment by villander** [comment]
@rwjblue can you close this in favor of embroider?

**Comment by villander** [comment]
@dgeb @stefanpenner can you close this in favor of embroider? we still do not know how code splitting and lazy loading will work in the ember.js ecosystem, it's very alpha with @ef4

**Comment by dgeb** [comment]
Yes, embroider will soon provide our packaging (via webpack, rollup, etc), so it's probably best to close this issue to avoid confusion.
